version: '3'
services:
  deploy:
    image: nsca_img
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - '1033:80'
    networks:
      - nscanetwork
networks:
  nscanetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.30.0.0/16
