export const COD_PLANILLA_ASEGURADOS = '01';
export const COD_PLANILLA_PENSIONISTAS = '02';
export const COD_PLANILLA_CONTINGENCIA_ADMINISTRATIVA = '03';
export const COD_PLANILLA_CONTINGENCIA_JUDICIAL = '04';
export const COD_TIPO_SOLICITUD_1990 = '01';
export const SISTEMA_LOGIN = 'NSCA'



